# Indexing, Iterating, and Math with Arrays

In this section we will learn how to perform some math operations and functions between NumPy arrays. We will also learn how to access individual elements within an array, as well as iterate these elements with `for` loops. 

## Indexing Arrays

Let's declare an array of four integer elements. 

In [1]:
import numpy as np 

a = np.array([67, 12, 19, 43])

Using 0-based indexing, we can access the first element. 

In [2]:
a[0]

67

We can access the third element. 

In [3]:
a[2]

19

We can also access the last element. 

In [4]:
a[-1]

43

Okay so what about arrays in higher dimensions? Here is a 2-dimensional array.

In [8]:
b = np.array([[  10,   20,   30,   40,   50],
              [ 100,  200,  300,  400,  500], 
              [1000, 2000, 3000, 4000, 5000]
             ])

b

array([[  10,   20,   30,   40,   50],
       [ 100,  200,  300,  400,  500],
       [1000, 2000, 3000, 4000, 5000]])

We can access the first row. 

In [9]:
b[0]

array([10, 20, 30, 40, 50])

we can access the third element in the second row using either of these syntaxes. 

In [11]:
b[1,2]

300

In [13]:
b[1][2]

300

We can also use slicing to grab ranges of the array, but we will save this for a later section. Just know the option is there. 

In [20]:
b[0:2, 3:5]

array([[ 40,  50],
       [400, 500]])

And here is one final example for a 3-dimensional array grabbing the center-most item, the `34`. 

In [21]:
my_image = np.array([
    [[0, 1, 3],
     [6, 2, 6], 
     [1, 5, 4]], 
    
    [[8, 3, 19],
     [33, 34, 11], 
     [13, 14, 89]], 
    
    [[14, 68, 17],
     [66, 84, 92], 
     [4, 2, 58]]
])

my_image[1][1][1]

34

## Basic Math Operators

Let's declare two different arrays, `a` and `b` which are 1-dimensional. 

In [30]:
a = np.array([.25, .5, .75])

b = np.array([4, 10, 100])

a.shape, b.shape, c.shape, d.shape

((3,), (3,), (3, 5), (3, 5))

We can add two arrays, adding each respective element together. 

In [32]:
a + b

array([  4.25,  10.5 , 100.75])

We can also subtract.

In [34]:
b - a

array([ 3.75,  9.5 , 99.25])

Multiply each respective element. 

In [35]:
a * b

array([ 1.,  5., 75.])

Or divide each respective element. 

In [36]:
a / b

array([0.0625, 0.05  , 0.0075])

You can even set another array `a` to be the exponents for `b`. 

In [48]:
b**a

array([ 1.41421356,  3.16227766, 31.6227766 ])

You can also use a single scalar value with any of these operators. It will just operate that value to each element in an array. If we multiply `a` by `100`, it will multiply each element of `a` by `100`. 

In [46]:
100*a

array([25., 50., 75.])

And of course, you can perform several operations at once. 

In [51]:
a**2 - a*b + b 

array([ 3.0625,  5.25  , 25.5625])

## Matrix Multiplication

One mathematical operation that should be called out is **matrix multiplication** as well as **matrix-vector multiplication**. But first, let's see an animation of a vector being multiplied against a matrix. 

<video src="https://github.com/thomasnield/anaconda_linear_algebra/raw/main/media/07_MatrixVectorMultiplicationScene.mp4" controls="controls" style="max-width: 730px;">
</video>


Numerically, a matrix-vector multiplication will multiply each respective row with each respective column, and sum the products together respectively. This is a very common operation, especially in machine learning and deep learning.

$ A\vec{v} $

$ = \begin{bmatrix} 1 & 2 \\ -1 & 1 \end{bmatrix} \begin{bmatrix} 0.5 \\ 1.5 \end{bmatrix} $

$ = \begin{bmatrix} (1)(0.5) + (2)(1.5) \\ (-1)(0.5) + (1)(1.5) \end{bmatrix} $

$ = \begin{bmatrix} 3.5 \\ 1 \end{bmatrix} $

This is executed using the `@` operator in NumPy. Note this is not commutative, and the order matters! In matrix-vector multiplication, the matrix is "applied" to the vector. 

In [52]:
import numpy as np 

A = np.array([[1,  2],
              [-1, 1]])

v = np.array([0.5, 1.5])

w = A @ v 
w

array([3.5, 1. ])

There is also matrix multiplication, which does a similar operation but with two matrices. It combines each respective row of the first matrix with each respective column of the second matrix, and multiplies and sums the respective elements together. 

$
\begin{aligned}
A &= BC \\
&= \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 2 & 1 \\ 0 & 1 \end{bmatrix} \\ &= \begin{bmatrix} (0 \cdot 2) + (1 \cdot 0) & (0 \cdot 1) + (1 \cdot 1) \\ (1 \cdot 2) + (0 \cdot 0) & (1 \cdot 1) + (0 \cdot 1) \end{bmatrix} \\
&= \begin{bmatrix} 0 & 1 \\ 2 & 1 \end{bmatrix}
\end{aligned}
$

It too is executed using the `@` operator. 

In [ ]:
import numpy as np 

v = np.array([1,1])

B = np.array([[0,1],[1,0]])
C = np.array([[2,1],[0,1]])

combined = C @ B 

combined @ v 

To learn more about these operations, check out the [Anaconda course on Linear Algebra](https://learning.anaconda.cloud/linear-algebra). It has spiffy animations too. 