# Joining and Splitting

In this section we will learn various ways to combine and split arrays. 

## Concatenation

If we want to **concatenate**, or append two arrays, we can use the `concatenate()` function.

In [3]:
import numpy as np

x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

x_and_y = np.concatenate([x, y])

print(x_and_y)

[10 20 30 40 50 60]


This will also work when we have arrays structured as a vertical column 

In [4]:
import numpy as np

x = np.array([[10], [20], [30]])
y = np.array([[40], [50], [60]])

x_and_y = np.concatenate((x, y))

print(x_and_y)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


## Stacking

Similar to concatenation, you can perform stacking which specifies an axis. `vstack()` will stack the arrays vertically. 

In [5]:
import numpy as np

x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

np.vstack((x, y))

array([[10, 20, 30],
       [40, 50, 60]])

`hstack()` will stack them horizontally. 

In [6]:
import numpy as np

x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

np.hstack((x, y))

array([10, 20, 30, 40, 50, 60])

`dstack()` will stack them along the z-axis, the depth or height axis. 

In [7]:
import numpy as np

x = np.array([10, 20, 30])
y = np.array([40, 50, 60])

np.dstack((x, y))

array([[[10, 40],
        [20, 50],
        [30, 60]]])

## Splitting

Let's create an array of 10 elements. 

In [8]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can use `array_split()` to split the array into two. 

In [9]:
np.array_split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

If there is a remainder (such as dividing an array of 11 elements into two arrays), it will omit the remainder elements. 

In [10]:
y = np.arange(0,11)

np.array_split(x,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

We can also leverage an `axis` parameter to make a split by columns. Below we split a 2x3 matrix into 3 arrays by columns. 

In [11]:
z = np.array([[10, 20, 30], 
            [40, 50, 60]])

np.array_split(z, 3, axis=1)

[array([[10],
        [40]]),
 array([[20],
        [50]]),
 array([[30],
        [60]])]

We could also achieve this using the `hsplit()` function, which performs a horizontal split and divides the columns. 

In [12]:
np.hsplit(z, 3)

[array([[10],
        [40]]),
 array([[20],
        [50]]),
 array([[30],
        [60]])]

The `vsplit()` will split vertically on each row. 

In [13]:
np.vsplit(z,2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

You can also unpack each of the individual arrays into variables. 

In [14]:
a,b,c = np.hsplit(z, 3)

In [15]:
a

array([[10],
       [40]])

In [16]:
b

array([[20],
       [50]])

In [17]:
c

array([[30],
       [60]])

Spend some time getting familiar with these operators and experiment with different shaped arrays. 

## EXERCISE 

Below we have a matrix $ X $. 

$$
X = \begin{bmatrix} 
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 
\end{bmatrix}
$$

Split and concatenate matrix $ X $ so we come up with this new matrix: 

$$
Y = \begin{bmatrix} 
1 & 2 \\ 
5 & 6 \\
3 & 4 \\
7 & 8 
\end{bmatrix}
$$

In [ ]:
## Put your code here 





### SCROLL DOWN FOR ANSWER
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
|<br>
v 

Use `hsplit()` to slice down the middle to create two 2x2 matrices, and then use `concatenate()` or `vstack()` to append the two pieces vertically. 

In [18]:
import numpy as np 

X = np.array([[1,2,3,4],
              [5,6,7,8]])


A,B = np.hsplit(X, 2)
np.vstack([A, B])

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])